#!/usr/bin/env tsx
/**
 * Subprocess agent runner for effectiveness evals.
 *
 * TRUST BOUNDARY: The bash tool executes arbitrary shell commands generated by
 * the LLM agent. This is intentional for local development fidelity but means
 * the sandbox relies on the user trusting their own skill/fixture content.
 * Sensitive env vars are stripped by the parent process. If community/third-party
 * skills are ever supported, this subprocess must run inside an OS-level sandbox
 * (container, namespace, or sandbox-exec).
 */
import { execSync } from 'node:child_process'
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import Anthropic from '@anthropic-ai/sdk'

const MAX_TURNS = 20
const TOOL_TIMEOUT_MS = 30_000

interface ToolCall {
  tool: string
  input: Record<string, unknown>
  output: string
}

interface Artifact {
  finalMessage: string
  toolCalls: ToolCall[]
}

function requireEnv(name: string): string {
  const value = process.env[name]
  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`)
  }
  return value
}

/**
 * Resolves a user-provided path against allowed base directories.
 * Prevents directory traversal by verifying the resolved path falls within one of the allowed bases.
 */
function resolveAndValidatePath(inputPath: string, allowedBases: [string, ...string[]]): string {
  const resolved = path.resolve(allowedBases[0], inputPath)

  const isAllowed = allowedBases.some(base => {
    const rel = path.relative(base, resolved)
    return !rel.startsWith('..') && !path.isAbsolute(rel)
  })
  if (!isAllowed) {
    throw new Error(`Path "${inputPath}" resolves outside allowed directories`)
  }

  return resolved
}

function executeBash(command: string, cwd: string): string {
  try {
    const output = execSync(command, {
      cwd,
      timeout: TOOL_TIMEOUT_MS,
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    })
    return output
  } catch (error: unknown) {
    if (
      error !== null &&
      typeof error === 'object' &&
      'stderr' in error &&
      typeof (error as { stderr: unknown }).stderr === 'string'
    ) {
      return (error as { stderr: string }).stderr
    }
    if (error instanceof Error) {
      return error.message
    }
    return 'Unknown error executing command'
  }
}

function executeReadFile(filePath: string, allowedBases: [string, ...string[]]): string {
  const resolved = resolveAndValidatePath(filePath, allowedBases)
  return readFileSync(resolved, 'utf-8')
}

function executeWriteFile(filePath: string, content: string, sandboxDir: string): string {
  const resolved = resolveAndValidatePath(filePath, [sandboxDir])
  mkdirSync(path.dirname(resolved), { recursive: true })
  writeFileSync(resolved, content, 'utf-8')
  return `File written: ${filePath}`
}

function executeListFiles(filePath: string, allowedBases: [string, ...string[]]): string {
  const resolved = resolveAndValidatePath(filePath, allowedBases)
  const entries = readdirSync(resolved, { withFileTypes: true })
  return entries.map(entry => (entry.isDirectory() ? `${entry.name}/` : entry.name)).join('\n')
}

function executeTool(
  toolName: string,
  input: Record<string, unknown>,
  sandboxDir: string,
  skillDir: string,
): string {
  const allowedReadBases: [string, ...string[]] = [sandboxDir, skillDir]

  switch (toolName) {
    case 'bash': {
      if (typeof input.command !== 'string') throw new Error('bash: missing or invalid "command"')
      return executeBash(input.command, sandboxDir)
    }
    case 'read_file': {
      if (typeof input.path !== 'string') throw new Error('read_file: missing or invalid "path"')
      return executeReadFile(input.path, allowedReadBases)
    }
    case 'write_file': {
      if (typeof input.path !== 'string') throw new Error('write_file: missing or invalid "path"')
      if (typeof input.content !== 'string')
        throw new Error('write_file: missing or invalid "content"')
      return executeWriteFile(input.path, input.content, sandboxDir)
    }
    case 'list_files': {
      if (typeof input.path !== 'string') throw new Error('list_files: missing or invalid "path"')
      return executeListFiles(input.path, allowedReadBases)
    }
    default:
      return `Unknown tool: ${toolName}`
  }
}

const TOOL_DEFINITIONS: Anthropic.Tool[] = [
  {
    name: 'bash',
    description: 'Execute a shell command in the workspace directory.',
    input_schema: {
      type: 'object' as const,
      properties: {
        command: { type: 'string', description: 'The shell command to execute' },
      },
      required: ['command'],
    },
  },
  {
    name: 'read_file',
    description: 'Read the contents of a file.',
    input_schema: {
      type: 'object' as const,
      properties: {
        path: {
          type: 'string',
          description: 'File path relative to the workspace directory',
        },
      },
      required: ['path'],
    },
  },
  {
    name: 'write_file',
    description: 'Write content to a file, creating directories as needed.',
    input_schema: {
      type: 'object' as const,
      properties: {
        path: {
          type: 'string',
          description: 'File path relative to the workspace directory',
        },
        content: { type: 'string', description: 'Content to write' },
      },
      required: ['path', 'content'],
    },
  },
  {
    name: 'list_files',
    description: 'List files and directories at a given path.',
    input_schema: {
      type: 'object' as const,
      properties: {
        path: {
          type: 'string',
          description: 'Directory path relative to the workspace',
        },
      },
      required: ['path'],
    },
  },
]

function buildSystemPrompt(skillContent: string, skillDir: string, sandboxDir: string): string {
  return [
    'You are an AI agent working in a project directory.',
    '',
    'The following skill has been loaded to help you with this task:',
    '',
    '<skill>',
    skillContent,
    '</skill>',
    '',
    `Skill resources (scripts, references, assets) are available at: ${skillDir}`,
    'You may read files from that directory if you need additional context.',
    '',
    `Your working directory is: ${sandboxDir}`,
    'Complete the task using the available tools.',
  ].join('\n')
}

async function runWithAnthropic(
  model: string,
  systemPrompt: string,
  prompt: string,
  toolCalls: ToolCall[],
  sandboxDir: string,
  skillDir: string,
): Promise<string> {
  const client = new Anthropic()

  const messages: Anthropic.MessageParam[] = [{ role: 'user', content: prompt }]

  let finalMessage = ''

  for (let turn = 0; turn < MAX_TURNS; turn++) {
    const response = await client.messages.create({
      model,
      max_tokens: 4096,
      system: systemPrompt,
      tools: TOOL_DEFINITIONS,
      messages,
    })

    const textBlocks = response.content.filter(
      (block): block is Anthropic.TextBlock => block.type === 'text',
    )
    if (textBlocks.length > 0) {
      finalMessage = textBlocks[textBlocks.length - 1]!.text
    }

    const toolUseBlocks = response.content.filter(
      (block): block is Anthropic.ToolUseBlock => block.type === 'tool_use',
    )

    if (response.stop_reason === 'end_turn' && toolUseBlocks.length === 0) {
      break
    }

    if (toolUseBlocks.length === 0) {
      break
    }

    messages.push({ role: 'assistant', content: response.content })

    const toolResults: Anthropic.ToolResultBlockParam[] = toolUseBlocks.map(block => {
      const input =
        typeof block.input === 'object' && block.input !== null
          ? (block.input as Record<string, unknown>)
          : {}
      let output: string
      try {
        output = executeTool(block.name, input, sandboxDir, skillDir)
      } catch (error: unknown) {
        output = error instanceof Error ? error.message : 'Tool execution failed'
      }

      toolCalls.push({ tool: block.name, input, output })

      return {
        type: 'tool_result' as const,
        tool_use_id: block.id,
        content: output,
      }
    })

    messages.push({ role: 'user', content: toolResults })
  }

  return finalMessage
}

async function runWithOpenAI(
  model: string,
  systemPrompt: string,
  prompt: string,
  toolCalls: ToolCall[],
  sandboxDir: string,
  skillDir: string,
): Promise<string> {
  const { default: OpenAI } = await import('openai')
  const client = new OpenAI()

  type OpenAITool = {
    type: 'function'
    function: { name: string; description: string; parameters: Record<string, unknown> }
  }

  const tools = TOOL_DEFINITIONS.map(t => ({
    type: 'function' as const,
    function: {
      name: t.name,
      description: t.description ?? '',
      parameters: t.input_schema as Record<string, unknown>,
    },
  })) satisfies OpenAITool[]

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const messages: any[] = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: prompt },
  ]

  let finalMessage = ''

  for (let turn = 0; turn < MAX_TURNS; turn++) {
    const response = await client.chat.completions.create({
      model,
      messages: messages as Parameters<typeof client.chat.completions.create>[0]['messages'],
      tools,
      tool_choice: 'auto',
    })

    const choice = response.choices[0]
    if (!choice) break

    const message = choice.message
    finalMessage = message.content ?? finalMessage

    if (!message.tool_calls || message.tool_calls.length === 0) {
      break
    }

    const functionCalls = message.tool_calls.filter(
      (tc): tc is Extract<typeof tc, { type: 'function' }> => tc.type === 'function',
    )

    if (functionCalls.length === 0) {
      break
    }

    messages.push({
      role: 'assistant',
      content: message.content,
      tool_calls: functionCalls.map(tc => ({
        id: tc.id,
        type: 'function',
        function: { name: tc.function.name, arguments: tc.function.arguments },
      })),
    })

    for (const call of functionCalls) {
      const input = JSON.parse(call.function.arguments || '{}') as Record<string, unknown>
      let output: string
      try {
        output = executeTool(call.function.name, input, sandboxDir, skillDir)
      } catch (error: unknown) {
        output = error instanceof Error ? error.message : 'Tool execution failed'
      }

      toolCalls.push({ tool: call.function.name, input, output })
      messages.push({
        role: 'tool',
        tool_call_id: call.id,
        content: output,
      })
    }
  }

  return finalMessage
}

async function runWithCopilot(
  model: string,
  systemPrompt: string,
  prompt: string,
  toolCalls: ToolCall[],
  sandboxDir: string,
  skillDir: string,
): Promise<string> {
  const existing = process.env.NODE_OPTIONS ?? ''
  if (!existing.includes('--disable-warning=ExperimentalWarning')) {
    process.env.NODE_OPTIONS = `${existing} --disable-warning=ExperimentalWarning`.trim()
  }

  const { CopilotClient, approveAll } = await import('@github/copilot-sdk')

  const makeHandler = (toolName: string) => {
    return (args: Record<string, unknown>): string => {
      let output: string
      try {
        output = executeTool(toolName, args, sandboxDir, skillDir)
      } catch (error: unknown) {
        output = error instanceof Error ? error.message : 'Tool execution failed'
      }
      toolCalls.push({ tool: toolName, input: args, output })
      return output
    }
  }

  const tools = [
    {
      name: 'bash',
      description: 'Execute a shell command in the workspace directory.',
      parameters: {
        type: 'object',
        properties: { command: { type: 'string', description: 'The shell command to execute' } },
        required: ['command'],
      },
      handler: makeHandler('bash'),
      skipPermission: true,
      overridesBuiltInTool: true,
    },
    {
      name: 'read_file',
      description: 'Read the contents of a file.',
      parameters: {
        type: 'object',
        properties: {
          path: { type: 'string', description: 'File path relative to the workspace directory' },
        },
        required: ['path'],
      },
      handler: makeHandler('read_file'),
      skipPermission: true,
      overridesBuiltInTool: true,
    },
    {
      name: 'write_file',
      description: 'Write content to a file, creating directories as needed.',
      parameters: {
        type: 'object',
        properties: {
          path: { type: 'string', description: 'File path relative to the workspace directory' },
          content: { type: 'string', description: 'Content to write' },
        },
        required: ['path', 'content'],
      },
      handler: makeHandler('write_file'),
      skipPermission: true,
      overridesBuiltInTool: true,
    },
    {
      name: 'list_files',
      description: 'List files and directories at a given path.',
      parameters: {
        type: 'object',
        properties: {
          path: { type: 'string', description: 'Directory path relative to the workspace' },
        },
        required: ['path'],
      },
      handler: makeHandler('list_files'),
      skipPermission: true,
      overridesBuiltInTool: true,
    },
  ]

  const client = new CopilotClient()
  try {
    const session = await client.createSession({
      onPermissionRequest: approveAll,
      systemMessage: { mode: 'replace', content: systemPrompt },
      tools,
      streaming: true,
      ...(model && { model }),
    })

    let modelSwitchError: Error | null = null
    session.on(event => {
      if (
        event.type === 'session.model_change' &&
        'data' in event &&
        event.data !== null &&
        typeof event.data === 'object'
      ) {
        const data = event.data as { newModel?: string }
        if (data.newModel && data.newModel !== model) {
          modelSwitchError = new Error(
            `Copilot switched model from requested "${model}" to "${data.newModel}". ` +
              'Aborting — model mismatch invalidates results.',
          )
          void session.abort()
        }
      }
    })

    try {
      const timeoutMs = Number(process.env.DOJO_TIMEOUT || '120000')
      const response = await session.sendAndWait({ prompt }, timeoutMs)
      if (modelSwitchError) {
        throw modelSwitchError
      }
      return response?.data.content ?? ''
    } catch (err) {
      if (modelSwitchError) {
        throw modelSwitchError
      }
      throw err
    } finally {
      await session.disconnect()
    }
  } finally {
    await client.stop()
  }
}

async function runWithVercel(
  model: string,
  systemPrompt: string,
  prompt: string,
  toolCalls: ToolCall[],
  sandboxDir: string,
  skillDir: string,
): Promise<string> {
  const { generateText, tool, stepCountIs } = await import('ai')
  const { z } = await import('zod/v4')

  const separatorIdx = model.indexOf('/')
  if (separatorIdx === -1) {
    throw new Error(
      `Vercel AI SDK model must be in the form "<provider>/<model-id>" (e.g. "openai/gpt-4o-mini"); got "${model}".`,
    )
  }

  const providerName = model.slice(0, separatorIdx)
  const modelId = model.slice(separatorIdx + 1)

  let createModel: (id: string) => Parameters<typeof generateText>[0]['model']

  if (providerName === 'openai') {
    const { openai } = await import('@ai-sdk/openai')
    createModel = openai as typeof createModel
  } else if (providerName === 'anthropic') {
    const { anthropic } = await import('@ai-sdk/anthropic')
    createModel = anthropic as typeof createModel
  } else {
    throw new Error(
      `Vercel provider does not support underlying provider "${providerName}". Use "openai/<model>" or "anthropic/<model>".`,
    )
  }

  const allowedReadBases: [string, ...string[]] = [sandboxDir, skillDir]

  const tools = {
    bash: tool({
      description: 'Execute a shell command in the workspace directory.',
      inputSchema: z.object({ command: z.string() }),
      execute: async ({ command }: { command: string }) => {
        const output = executeBash(command, sandboxDir)
        toolCalls.push({ tool: 'bash', input: { command }, output })
        return output
      },
    }),
    read_file: tool({
      description: 'Read the contents of a file.',
      inputSchema: z.object({ path: z.string() }),
      execute: async ({ path: filePath }: { path: string }) => {
        const output = executeReadFile(filePath, allowedReadBases)
        toolCalls.push({ tool: 'read_file', input: { path: filePath }, output })
        return output
      },
    }),
    write_file: tool({
      description: 'Write content to a file, creating directories as needed.',
      inputSchema: z.object({ path: z.string(), content: z.string() }),
      execute: async ({ path: filePath, content }: { path: string; content: string }) => {
        const output = executeWriteFile(filePath, content, sandboxDir)
        toolCalls.push({ tool: 'write_file', input: { path: filePath, content }, output })
        return output
      },
    }),
    list_files: tool({
      description: 'List files and directories at a given path.',
      inputSchema: z.object({ path: z.string() }),
      execute: async ({ path: filePath }: { path: string }) => {
        const output = executeListFiles(filePath, allowedReadBases)
        toolCalls.push({ tool: 'list_files', input: { path: filePath }, output })
        return output
      },
    }),
  }

  const result = await generateText({
    model: createModel(modelId),
    system: systemPrompt,
    prompt,
    tools,
    stopWhen: stepCountIs(MAX_TURNS),
  })

  return result.text
}

async function main(): Promise<void> {
  const provider = requireEnv('DOJO_PROVIDER')
  const sandboxDir = requireEnv('DOJO_SANDBOX_DIR')
  const skillDir = requireEnv('DOJO_SKILL_DIR')
  const prompt = requireEnv('DOJO_PROMPT')
  const model = requireEnv('DOJO_MODEL')
  const artifactPath = requireEnv('DOJO_ARTIFACT_PATH')

  const toolCalls: ToolCall[] = []

  const timeoutMs = Number(process.env.DOJO_TIMEOUT || '120000')
  const timeoutId = setTimeout(() => {
    console.error(`Agent timed out after ${timeoutMs}ms`)
    const artifact: Artifact = { finalMessage: '', toolCalls }
    mkdirSync(path.dirname(artifactPath), { recursive: true })
    writeFileSync(artifactPath, JSON.stringify(artifact, null, 2), 'utf-8')
    process.exit(1)
  }, timeoutMs)
  timeoutId.unref()

  const skillContent = readFileSync(path.join(skillDir, 'SKILL.md'), 'utf-8')
  const systemPrompt = buildSystemPrompt(skillContent, skillDir, sandboxDir)

  let finalMessage: string

  switch (provider) {
    case 'anthropic':
      finalMessage = await runWithAnthropic(
        model,
        systemPrompt,
        prompt,
        toolCalls,
        sandboxDir,
        skillDir,
      )
      break
    case 'openai':
      finalMessage = await runWithOpenAI(
        model,
        systemPrompt,
        prompt,
        toolCalls,
        sandboxDir,
        skillDir,
      )
      break
    case 'copilot':
      finalMessage = await runWithCopilot(
        model,
        systemPrompt,
        prompt,
        toolCalls,
        sandboxDir,
        skillDir,
      )
      break
    case 'vercel':
      finalMessage = await runWithVercel(
        model,
        systemPrompt,
        prompt,
        toolCalls,
        sandboxDir,
        skillDir,
      )
      break
    default:
      throw new Error(`Unsupported provider: "${provider}"`)
  }

  clearTimeout(timeoutId)

  const artifact: Artifact = { finalMessage, toolCalls }
  mkdirSync(path.dirname(artifactPath), { recursive: true })
  writeFileSync(artifactPath, JSON.stringify(artifact, null, 2), 'utf-8')
}

main().catch((error: unknown) => {
  console.error('Agent runner failed:', error)
  process.exit(1)
})
